# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 92156dfebbbfe96c6602ecbdf64e9b6d22d8f7bdd7cdb7b3c403011f3f1f41e5d35fbe050051c1e0abd6d87d7527d8cddee6eba63dd6e5fe6e3c6436d486419d

test:
  secret_key_base: 9f97d1b11ccbf23b818cc27c26de208ff913670a40335d7eb1ac8503993fc99d24fb6c72ef2a329b75035699566270a6fb20babc858a4f46d854d58143278407

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
